[programs.localnet]
hello_world = "6xBtgAHiZvQUNcApL36wj3a94soEocHc5QaowVR8Kyr"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/mehulghoderao/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
